# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matplt3dview.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1288, 832)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mjp-multijet-printing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab2dview = QtWidgets.QTabWidget(self.centralwidget)
        self.tab2dview.setGeometry(QtCore.QRect(0, 0, 811, 511))
        self.tab2dview.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tab2dview.setAutoFillBackground(False)
        self.tab2dview.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab2dview.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab2dview.setElideMode(QtCore.Qt.ElideNone)
        self.tab2dview.setObjectName("tab2dview")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.view3d = QtWidgets.QWidget(self.tab)
        self.view3d.setGeometry(QtCore.QRect(1, 1, 761, 471))
        self.view3d.setObjectName("view3d")
        self.tab2dview.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layer = QtWidgets.QLabel(self.tab_2)
        self.layer.setGeometry(QtCore.QRect(0, 0, 751, 471))
        self.layer.setAlignment(QtCore.Qt.AlignCenter)
        self.layer.setObjectName("layer")
        self.verticalSlider = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider.setGeometry(QtCore.QRect(770, 40, 22, 401))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.tab2dview.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.LAYER_VIEW2D = QtWidgets.QWidget(self.tab_7)
        self.LAYER_VIEW2D.setGeometry(QtCore.QRect(1, 1, 800, 490))
        self.LAYER_VIEW2D.setObjectName("LAYER_VIEW2D")
        self.tab2dview.addTab(self.tab_7, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(810, 0, 471, 481))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 421, 111))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 441, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(17, 160, 431, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(290, 200, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox.setEnabled(True)
        self.doubleSpinBox.setGeometry(QtCore.QRect(140, 200, 141, 31))
        self.doubleSpinBox.setAutoFillBackground(False)
        self.doubleSpinBox.setAccelerated(False)
        self.doubleSpinBox.setMinimum(1.0)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Next_layer = QtWidgets.QPushButton(self.tab_5)
        self.Next_layer.setGeometry(QtCore.QRect(330, 180, 93, 28))
        self.Next_layer.setObjectName("Next_layer")
        self.previous_layer = QtWidgets.QPushButton(self.tab_5)
        self.previous_layer.setGeometry(QtCore.QRect(120, 180, 93, 28))
        self.previous_layer.setObjectName("previous_layer")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(810, 480, 471, 301))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_6)
        self.textBrowser.setGeometry(QtCore.QRect(0, -10, 471, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 510, 791, 261))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_6.setMouseTracking(False)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 171, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 171, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 171, 31))
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 151, 31))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.tabWidget_2.raise_()
        self.tabWidget_3.raise_()
        self.groupBox.raise_()
        self.tab2dview.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1288, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
         
        
        self.retranslateUi(MainWindow)
        self.tab2dview.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DP"))
        self.tab2dview.setTabText(self.tab2dview.indexOf(self.tab), _translate("MainWindow", "3D View"))
        self.layer.setText(_translate("MainWindow", "Layers Display"))
        self.tab2dview.setTabText(self.tab2dview.indexOf(self.tab_2), _translate("MainWindow", "2D View"))
        self.tab2dview.setTabText(self.tab2dview.indexOf(self.tab_7), _translate("MainWindow", "Page"))
        self.pushButton_3.setText(_translate("MainWindow", "Open STL file"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Object Placement"))
        self.pushButton.setText(_translate("MainWindow", "Slice with Slic3r"))
        self.label.setText(_translate("MainWindow", "Slic3r Settings"))
        self.label_2.setText(_translate("MainWindow", "Layer Height:"))
        self.label_5.setText(_translate("MainWindow", "mm"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Slice"))
        self.Next_layer.setText(_translate("MainWindow", "Next layer"))
        self.previous_layer.setText(_translate("MainWindow", "previous layer"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Printer Control"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Console"))
        self.groupBox.setTitle(_translate("MainWindow", "Printer Status"))
        self.label_6.setText(_translate("MainWindow", "Connection:"))
        self.label_7.setText(_translate("MainWindow", "Machine State:"))
        self.label_8.setText(_translate("MainWindow", "Estimated Time:"))
        self.label_9.setText(_translate("MainWindow", "Model Name:"))
        self.label_3.setText(_translate("MainWindow", "Connected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

