# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatedProgramGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1302, 831)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mjp-multijet-printing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab2dview = QtWidgets.QTabWidget(self.centralwidget)
        self.tab2dview.setGeometry(QtCore.QRect(0, 0, 811, 511))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        self.tab2dview.setFont(font)
        self.tab2dview.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tab2dview.setAutoFillBackground(False)
        self.tab2dview.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab2dview.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab2dview.setElideMode(QtCore.Qt.ElideNone)
        self.tab2dview.setObjectName("tab2dview")
        self.bed_view = QtWidgets.QWidget()
        self.bed_view.setObjectName("bed_view")
        self.BedView = QtWidgets.QWidget(self.bed_view)
        self.BedView.setGeometry(QtCore.QRect(1, 1, 800, 490))
        self.BedView.setObjectName("BedView")
        self.tab2dview.addTab(self.bed_view, "")
        self.view2d = QtWidgets.QWidget()
        self.view2d.setObjectName("view2d")
        self.verticalSlider = QtWidgets.QSlider(self.view2d)
        self.verticalSlider.setGeometry(QtCore.QRect(780, 20, 22, 461))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.LAYER_VIEW2D = QtWidgets.QWidget(self.view2d)
        self.LAYER_VIEW2D.setGeometry(QtCore.QRect(10, 0, 771, 490))
        self.LAYER_VIEW2D.setObjectName("LAYER_VIEW2D")
        self.tab2dview.addTab(self.view2d, "")
        self.viewlayers = QtWidgets.QWidget()
        self.viewlayers.setObjectName("viewlayers")
        self.view3d = QtWidgets.QWidget(self.viewlayers)
        self.view3d.setGeometry(QtCore.QRect(1, 1, 800, 490))
        self.view3d.setObjectName("view3d")
        self.tab2dview.addTab(self.viewlayers, "")
        self.PrinterSettingstab = QtWidgets.QTabWidget(self.centralwidget)
        self.PrinterSettingstab.setGeometry(QtCore.QRect(810, 0, 491, 501))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(10)
        self.PrinterSettingstab.setFont(font)
        self.PrinterSettingstab.setObjectName("PrinterSettingstab")
        self.control_tab_4 = QtWidgets.QWidget()
        self.control_tab_4.setObjectName("control_tab_4")
        self.slicer = QtWidgets.QPushButton(self.control_tab_4)
        self.slicer.setGeometry(QtCore.QRect(250, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.slicer.setFont(font)
        self.slicer.setObjectName("slicer")
        self.Printsettings = QtWidgets.QLabel(self.control_tab_4)
        self.Printsettings.setGeometry(QtCore.QRect(10, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Printsettings.setFont(font)
        self.Printsettings.setScaledContents(True)
        self.Printsettings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Printsettings.setWordWrap(False)
        self.Printsettings.setObjectName("Printsettings")
        self.Selectedlayer = QtWidgets.QLabel(self.control_tab_4)
        self.Selectedlayer.setGeometry(QtCore.QRect(0, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Selectedlayer.setFont(font)
        self.Selectedlayer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Selectedlayer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Selectedlayer.setScaledContents(True)
        self.Selectedlayer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Selectedlayer.setWordWrap(False)
        self.Selectedlayer.setObjectName("Selectedlayer")
        self.line = QtWidgets.QFrame(self.control_tab_4)
        self.line.setGeometry(QtCore.QRect(10, 120, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.opensvg = QtWidgets.QPushButton(self.control_tab_4)
        self.opensvg.setGeometry(QtCore.QRect(10, 20, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.opensvg.setFont(font)
        self.opensvg.setObjectName("opensvg")
        self.uploaddata = QtWidgets.QPushButton(self.control_tab_4)
        self.uploaddata.setEnabled(True)  #changed
        self.uploaddata.setGeometry(QtCore.QRect(290, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.uploaddata.setFont(font)
        self.uploaddata.setObjectName("uploaddata")
        self.layernumb = QtWidgets.QSpinBox(self.control_tab_4)
        self.layernumb.setGeometry(QtCore.QRect(200, 150, 71, 31))
        self.layernumb.setMaximum(1000)
        self.layernumb.setObjectName("layernumb")
        self.print = QtWidgets.QPushButton(self.control_tab_4)
        self.print.setEnabled(True)
        self.print.setGeometry(QtCore.QRect(10, 190, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.print.setFont(font)
        self.print.setCheckable(False)
        self.print.setAutoDefault(False)
        self.print.setDefault(False)
        self.print.setFlat(False)
        self.print.setObjectName("print")
        self.pauseprint = QtWidgets.QPushButton(self.control_tab_4)
        self.pauseprint.setEnabled(False)
        self.pauseprint.setGeometry(QtCore.QRect(10, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pauseprint.setFont(font)
        self.pauseprint.setObjectName("pauseprint")
        self.cancelprint = QtWidgets.QPushButton(self.control_tab_4)
        self.cancelprint.setEnabled(False)
        self.cancelprint.setGeometry(QtCore.QRect(250, 230, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelprint.setFont(font)
        self.cancelprint.setObjectName("cancelprint")
        self.moveposx = QtWidgets.QPushButton(self.control_tab_4)
        self.moveposx.setEnabled(False)
        self.moveposx.setGeometry(QtCore.QRect(370, 370, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.moveposx.setFont(font)
        self.moveposx.setObjectName("moveposx")
        self.testprinthead = QtWidgets.QPushButton(self.control_tab_4)
        self.testprinthead.setEnabled(False)
        self.testprinthead.setGeometry(QtCore.QRect(250, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testprinthead.setFont(font)
        self.testprinthead.setObjectName("testprinthead")
        self.movexlabel = QtWidgets.QLabel(self.control_tab_4)
        self.movexlabel.setGeometry(QtCore.QRect(10, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movexlabel.setFont(font)
        self.movexlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.movexlabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.movexlabel.setScaledContents(True)
        self.movexlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.movexlabel.setWordWrap(False)
        self.movexlabel.setObjectName("movexlabel")
        self.movenegx = QtWidgets.QPushButton(self.control_tab_4)
        self.movenegx.setEnabled(False)
        self.movenegx.setGeometry(QtCore.QRect(150, 370, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movenegx.setFont(font)
        self.movenegx.setObjectName("movenegx")
        self.moveYlabel = QtWidgets.QLabel(self.control_tab_4)
        self.moveYlabel.setGeometry(QtCore.QRect(10, 420, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moveYlabel.setFont(font)
        self.moveYlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.moveYlabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.moveYlabel.setScaledContents(True)
        self.moveYlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.moveYlabel.setWordWrap(False)
        self.moveYlabel.setObjectName("moveYlabel")
        self.movenegy = QtWidgets.QPushButton(self.control_tab_4)
        self.movenegy.setEnabled(False)
        self.movenegy.setGeometry(QtCore.QRect(150, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movenegy.setFont(font)
        self.movenegy.setObjectName("movenegy")
        self.moveposy = QtWidgets.QPushButton(self.control_tab_4)
        self.moveposy.setEnabled(False)
        self.moveposy.setGeometry(QtCore.QRect(370, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.moveposy.setFont(font)
        self.moveposy.setObjectName("moveposy")
        self.line_6 = QtWidgets.QFrame(self.control_tab_4)
        self.line_6.setGeometry(QtCore.QRect(0, 260, 491, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.stopx = QtWidgets.QPushButton(self.control_tab_4)
        self.stopx.setEnabled(False)
        self.stopx.setGeometry(QtCore.QRect(250, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopx.setFont(font)
        self.stopx.setObjectName("stopx")
        self.stopy = QtWidgets.QPushButton(self.control_tab_4)
        self.stopy.setEnabled(False)
        self.stopy.setGeometry(QtCore.QRect(250, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopy.setFont(font)
        self.stopy.setObjectName("stopy")
        self.homebutton = QtWidgets.QPushButton(self.control_tab_4)
        self.homebutton.setEnabled(False)
        self.homebutton.setGeometry(QtCore.QRect(20, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.homebutton.setFont(font)
        self.homebutton.setObjectName("homebutton")
        self.Printsettings_2 = QtWidgets.QLabel(self.control_tab_4)
        self.Printsettings_2.setGeometry(QtCore.QRect(10, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Printsettings_2.setFont(font)
        self.Printsettings_2.setScaledContents(True)
        self.Printsettings_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Printsettings_2.setWordWrap(False)
        self.Printsettings_2.setObjectName("Printsettings_2")
        self.manualON = QtWidgets.QPushButton(self.control_tab_4)
        self.manualON.setGeometry(QtCore.QRect(180, 280, 121, 28))
        self.manualON.setObjectName("manualON")
        self.manualOFF = QtWidgets.QPushButton(self.control_tab_4)
        self.manualOFF.setEnabled(False)
        self.manualOFF.setGeometry(QtCore.QRect(320, 280, 131, 28))
        self.manualOFF.setObjectName("manualOFF")
        self.PrinterSettingstab.addTab(self.control_tab_4, "")
        self.Printer_Settings = QtWidgets.QWidget()
        self.Printer_Settings.setObjectName("Printer_Settings")
        self.bedSizelabel = QtWidgets.QLabel(self.Printer_Settings)
        self.bedSizelabel.setGeometry(QtCore.QRect(10, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bedSizelabel.setFont(font)
        self.bedSizelabel.setScaledContents(True)
        self.bedSizelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bedSizelabel.setWordWrap(False)
        self.bedSizelabel.setObjectName("bedSizelabel")
        self.xybedaxisLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.xybedaxisLabel.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xybedaxisLabel.setFont(font)
        self.xybedaxisLabel.setScaledContents(True)
        self.xybedaxisLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xybedaxisLabel.setWordWrap(False)
        self.xybedaxisLabel.setObjectName("xybedaxisLabel")
        self.bedXaxis = QtWidgets.QSpinBox(self.Printer_Settings)
        self.bedXaxis.setGeometry(QtCore.QRect(150, 50, 81, 31))
        self.bedXaxis.setMaximum(10000)
        self.bedXaxis.setProperty("value", 150)
        self.bedXaxis.setDisplayIntegerBase(10)
        self.bedXaxis.setObjectName("bedXaxis")
        self.mmLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.mmLabel.setGeometry(QtCore.QRect(370, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mmLabel.setFont(font)
        self.mmLabel.setScaledContents(True)
        self.mmLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mmLabel.setWordWrap(False)
        self.mmLabel.setObjectName("mmLabel")
        self.xlabel = QtWidgets.QLabel(self.Printer_Settings)
        self.xlabel.setGeometry(QtCore.QRect(250, 50, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel.setFont(font)
        self.xlabel.setScaledContents(True)
        self.xlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel.setWordWrap(False)
        self.xlabel.setObjectName("xlabel")
        self.XYresolnLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.XYresolnLabel.setGeometry(QtCore.QRect(10, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.XYresolnLabel.setFont(font)
        self.XYresolnLabel.setScaledContents(True)
        self.XYresolnLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.XYresolnLabel.setWordWrap(False)
        self.XYresolnLabel.setObjectName("XYresolnLabel")
        self.Xdpi = QtWidgets.QSpinBox(self.Printer_Settings)
        self.Xdpi.setGeometry(QtCore.QRect(150, 170, 81, 31))
        self.Xdpi.setMaximum(2000)
        self.Xdpi.setProperty("value", 329)
        self.Xdpi.setObjectName("Xdpi")
        self.xlabel2 = QtWidgets.QLabel(self.Printer_Settings)
        self.xlabel2.setGeometry(QtCore.QRect(250, 170, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2.setFont(font)
        self.xlabel2.setScaledContents(True)
        self.xlabel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2.setWordWrap(False)
        self.xlabel2.setObjectName("xlabel2")
        self.Ydpi = QtWidgets.QSpinBox(self.Printer_Settings)
        self.Ydpi.setGeometry(QtCore.QRect(270, 170, 81, 31))
        self.Ydpi.setMaximum(2000)
        self.Ydpi.setProperty("value", 185)
        self.Ydpi.setObjectName("Ydpi")
        self.DpiLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.DpiLabel.setGeometry(QtCore.QRect(390, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DpiLabel.setFont(font)
        self.DpiLabel.setScaledContents(True)
        self.DpiLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DpiLabel.setWordWrap(False)
        self.DpiLabel.setObjectName("DpiLabel")
        self.line_4 = QtWidgets.QFrame(self.Printer_Settings)
        self.line_4.setGeometry(QtCore.QRect(10, 110, 461, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.jetFreqlabel = QtWidgets.QLabel(self.Printer_Settings)
        self.jetFreqlabel.setGeometry(QtCore.QRect(10, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jetFreqlabel.setFont(font)
        self.jetFreqlabel.setScaledContents(True)
        self.jetFreqlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.jetFreqlabel.setWordWrap(False)
        self.jetFreqlabel.setObjectName("jetFreqlabel")
        self.jet_freq = QtWidgets.QSpinBox(self.Printer_Settings)
        self.jet_freq.setGeometry(QtCore.QRect(150, 210, 81, 31))
        self.jet_freq.setMinimum(1)
        self.jet_freq.setMaximum(100)
        self.jet_freq.setObjectName("jet_freq")
        self.perpixelLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.perpixelLabel.setGeometry(QtCore.QRect(240, 210, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.perpixelLabel.setFont(font)
        self.perpixelLabel.setScaledContents(True)
        self.perpixelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.perpixelLabel.setWordWrap(False)
        self.perpixelLabel.setObjectName("perpixelLabel")
        self.line_14 = QtWidgets.QFrame(self.Printer_Settings)
        self.line_14.setGeometry(QtCore.QRect(10, 260, 461, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.motionAxesLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.motionAxesLabel.setGeometry(QtCore.QRect(10, 290, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.motionAxesLabel.setFont(font)
        self.motionAxesLabel.setScaledContents(True)
        self.motionAxesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.motionAxesLabel.setWordWrap(False)
        self.motionAxesLabel.setObjectName("motionAxesLabel")
        self.printResolutionLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.printResolutionLabel.setGeometry(QtCore.QRect(10, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.printResolutionLabel.setFont(font)
        self.printResolutionLabel.setScaledContents(True)
        self.printResolutionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printResolutionLabel.setWordWrap(False)
        self.printResolutionLabel.setObjectName("printResolutionLabel")
        self.Xmotionlabel = QtWidgets.QLabel(self.Printer_Settings)
        self.Xmotionlabel.setGeometry(QtCore.QRect(20, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Xmotionlabel.setFont(font)
        self.Xmotionlabel.setScaledContents(True)
        self.Xmotionlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Xmotionlabel.setWordWrap(False)
        self.Xmotionlabel.setObjectName("Xmotionlabel")
        self.YmotionLabel = QtWidgets.QLabel(self.Printer_Settings)
        self.YmotionLabel.setGeometry(QtCore.QRect(20, 390, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YmotionLabel.setFont(font)
        self.YmotionLabel.setScaledContents(True)
        self.YmotionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.YmotionLabel.setWordWrap(False)
        self.YmotionLabel.setObjectName("YmotionLabel")
        self.Xmicronslabel = QtWidgets.QLabel(self.Printer_Settings)
        self.Xmicronslabel.setGeometry(QtCore.QRect(270, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Xmicronslabel.setFont(font)
        self.Xmicronslabel.setScaledContents(True)
        self.Xmicronslabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Xmicronslabel.setWordWrap(False)
        self.Xmicronslabel.setObjectName("Xmicronslabel")
        self.Ymicronslabel = QtWidgets.QLabel(self.Printer_Settings)
        self.Ymicronslabel.setGeometry(QtCore.QRect(270, 390, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ymicronslabel.setFont(font)
        self.Ymicronslabel.setScaledContents(True)
        self.Ymicronslabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Ymicronslabel.setWordWrap(False)
        self.Ymicronslabel.setObjectName("Ymicronslabel")
        self.xmotionresln = QtWidgets.QDoubleSpinBox(self.Printer_Settings)
        self.xmotionresln.setEnabled(False)
        self.xmotionresln.setGeometry(QtCore.QRect(160, 340, 71, 31))
        self.xmotionresln.setDecimals(1)
        self.xmotionresln.setMaximum(1000.0)
        self.xmotionresln.setSingleStep(0.5)
        self.xmotionresln.setProperty("value", 0.0)
        self.xmotionresln.setObjectName("xmotionresln")
        self.ymotionresln = QtWidgets.QDoubleSpinBox(self.Printer_Settings)
        self.ymotionresln.setEnabled(False)
        self.ymotionresln.setGeometry(QtCore.QRect(160, 390, 71, 31))
        self.ymotionresln.setDecimals(1)
        self.ymotionresln.setMaximum(1000.0)
        self.ymotionresln.setSingleStep(0.5)
        self.ymotionresln.setObjectName("ymotionresln")
        self.bedYaxis = QtWidgets.QSpinBox(self.Printer_Settings)
        self.bedYaxis.setGeometry(QtCore.QRect(270, 50, 81, 31))
        self.bedYaxis.setMaximum(10000)
        self.bedYaxis.setProperty("value", 150)
        self.bedYaxis.setDisplayIntegerBase(10)
        self.bedYaxis.setObjectName("bedYaxis")
        self.checkBoxmotion = QtWidgets.QCheckBox(self.Printer_Settings)
        self.checkBoxmotion.setGeometry(QtCore.QRect(270, 290, 81, 31))
        self.checkBoxmotion.setText("")
        self.checkBoxmotion.setObjectName("checkBoxmotion")
        self.xybedaxisLabel_2 = QtWidgets.QLabel(self.Printer_Settings)
        self.xybedaxisLabel_2.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xybedaxisLabel_2.setFont(font)
        self.xybedaxisLabel_2.setScaledContents(True)
        self.xybedaxisLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xybedaxisLabel_2.setWordWrap(False)
        self.xybedaxisLabel_2.setObjectName("xybedaxisLabel_2")
        self.bedXorigin = QtWidgets.QSpinBox(self.Printer_Settings)
        self.bedXorigin.setGeometry(QtCore.QRect(150, 80, 81, 31))
        self.bedXorigin.setMaximum(10000)
        self.bedXorigin.setProperty("value", 0)
        self.bedXorigin.setDisplayIntegerBase(10)
        self.bedXorigin.setObjectName("bedXorigin")
        self.xlabel_2 = QtWidgets.QLabel(self.Printer_Settings)
        self.xlabel_2.setGeometry(QtCore.QRect(250, 80, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel_2.setFont(font)
        self.xlabel_2.setScaledContents(True)
        self.xlabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel_2.setWordWrap(False)
        self.xlabel_2.setObjectName("xlabel_2")
        self.bedYorigin = QtWidgets.QSpinBox(self.Printer_Settings)
        self.bedYorigin.setGeometry(QtCore.QRect(270, 80, 81, 31))
        self.bedYorigin.setMaximum(10000)
        self.bedYorigin.setProperty("value", 0)
        self.bedYorigin.setDisplayIntegerBase(10)
        self.bedYorigin.setObjectName("bedYorigin")
        self.mmLabel_2 = QtWidgets.QLabel(self.Printer_Settings)
        self.mmLabel_2.setGeometry(QtCore.QRect(370, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mmLabel_2.setFont(font)
        self.mmLabel_2.setScaledContents(True)
        self.mmLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mmLabel_2.setWordWrap(False)
        self.mmLabel_2.setObjectName("mmLabel_2")
        self.PrinterSettingstab.addTab(self.Printer_Settings, "")
        self.Console = QtWidgets.QTabWidget(self.centralwidget)
        self.Console.setGeometry(QtCore.QRect(810, 500, 491, 281))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(11)
        self.Console.setFont(font)
        self.Console.setObjectName("Console")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_6)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 491, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser.setPalette(palette)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.Console.addTab(self.tab_6, "")
        self.groupBoxstatus = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxstatus.setGeometry(QtCore.QRect(10, 510, 791, 261))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBoxstatus.setFont(font)
        self.groupBoxstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxstatus.setFlat(False)
        self.groupBoxstatus.setCheckable(False)
        self.groupBoxstatus.setObjectName("groupBoxstatus")
        self.connection = QtWidgets.QLabel(self.groupBoxstatus)
        self.connection.setEnabled(True)
        self.connection.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.connection.setFont(font)
        self.connection.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.connection.setMouseTracking(False)
        self.connection.setTextFormat(QtCore.Qt.AutoText)
        self.connection.setWordWrap(False)
        self.connection.setObjectName("connection")
        self.currentprocess = QtWidgets.QLabel(self.groupBoxstatus)
        self.currentprocess.setGeometry(QtCore.QRect(10, 110, 171, 31))
        self.currentprocess.setObjectName("currentprocess")
        self.layerinfo = QtWidgets.QLabel(self.groupBoxstatus)
        self.layerinfo.setGeometry(QtCore.QRect(10, 160, 171, 31))
        self.layerinfo.setObjectName("layerinfo")
        self.cadmodelname = QtWidgets.QLabel(self.groupBoxstatus)
        self.cadmodelname.setGeometry(QtCore.QRect(10, 220, 171, 31))
        self.cadmodelname.setObjectName("cadmodelname")
        self.connectionstatus = QtWidgets.QLabel(self.groupBoxstatus)
        self.connectionstatus.setGeometry(QtCore.QRect(340, 50, 241, 31))
        self.connectionstatus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.connectionstatus.setObjectName("connectionstatus")
        self.process = QtWidgets.QLabel(self.groupBoxstatus)
        self.process.setGeometry(QtCore.QRect(340, 110, 241, 31))
        self.process.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.process.setObjectName("process")
        self.layernum = QtWidgets.QLabel(self.groupBoxstatus)
        self.layernum.setGeometry(QtCore.QRect(340, 160, 241, 31))
        self.layernum.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.layernum.setText("")
        self.layernum.setObjectName("layernum")
        self.modelname = QtWidgets.QLabel(self.groupBoxstatus)
        self.modelname.setGeometry(QtCore.QRect(340, 220, 241, 31))
        self.modelname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.modelname.setText("")
        self.modelname.setObjectName("modelname")
        self.PrinterSettingstab.raise_()
        self.Console.raise_()
        self.groupBoxstatus.raise_()
        self.tab2dview.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab2dview.setCurrentIndex(0)
        self.PrinterSettingstab.setCurrentIndex(0)
        self.Console.setCurrentIndex(0)
        self.checkBoxmotion.clicked['bool'].connect(self.xmotionresln.setEnabled)
        self.checkBoxmotion.clicked['bool'].connect(self.ymotionresln.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DP"))
        self.tab2dview.setTabText(self.tab2dview.indexOf(self.bed_view), _translate("MainWindow", "Print Bed View"))
        self.tab2dview.setTabText(self.tab2dview.indexOf(self.view2d), _translate("MainWindow", "2D View"))
        self.tab2dview.setTabText(self.tab2dview.indexOf(self.viewlayers), _translate("MainWindow", "3D View"))
        self.slicer.setText(_translate("MainWindow", "Slice with Slic3r"))
        self.Printsettings.setText(_translate("MainWindow", "Print Settings"))
        self.Selectedlayer.setText(_translate("MainWindow", "Selected Layer to print :"))
        self.opensvg.setText(_translate("MainWindow", "Open SVG Format"))
        self.uploaddata.setText(_translate("MainWindow", "Upload Data"))
        self.print.setText(_translate("MainWindow", "PRINT"))
        self.pauseprint.setText(_translate("MainWindow", "PAUSE"))
        self.cancelprint.setText(_translate("MainWindow", "CANCEL"))
        self.moveposx.setText(_translate("MainWindow", "+X >>|"))
        self.testprinthead.setText(_translate("MainWindow", "TEST PRINTHEAD"))
        self.movexlabel.setText(_translate("MainWindow", "MOVE IN X :"))
        self.movenegx.setText(_translate("MainWindow", "|<<  -X"))
        self.moveYlabel.setText(_translate("MainWindow", "MOVE IN Y :"))
        self.movenegy.setText(_translate("MainWindow", "|<< -Y"))
        self.moveposy.setText(_translate("MainWindow", "+Y >>|"))
        self.stopx.setText(_translate("MainWindow", "STOPX"))
        self.stopy.setText(_translate("MainWindow", "STOPY"))
        self.homebutton.setText(_translate("MainWindow", "HOME"))
        self.Printsettings_2.setText(_translate("MainWindow", "Manual Control:"))
        self.manualON.setText(_translate("MainWindow", "ON"))
        self.manualOFF.setText(_translate("MainWindow", "OFF"))
        self.PrinterSettingstab.setTabText(self.PrinterSettingstab.indexOf(self.control_tab_4), _translate("MainWindow", "Control"))
        self.bedSizelabel.setText(_translate("MainWindow", "Bed Size dimensions:"))
        self.xybedaxisLabel.setText(_translate("MainWindow", "X axis . Y axis:"))
        self.mmLabel.setText(_translate("MainWindow", "Millimeters"))
        self.xlabel.setText(_translate("MainWindow", "x"))
        self.XYresolnLabel.setText(_translate("MainWindow", "X-Y resolution:"))
        self.xlabel2.setText(_translate("MainWindow", "x"))
        self.DpiLabel.setText(_translate("MainWindow", "DPI"))
        self.jetFreqlabel.setText(_translate("MainWindow", "Jet frequency:"))
        self.perpixelLabel.setText(_translate("MainWindow", "/Pixel "))
        self.motionAxesLabel.setText(_translate("MainWindow", "Motion Axes Resolution (Optional):"))
        self.printResolutionLabel.setText(_translate("MainWindow", "Print Resolution:"))
        self.Xmotionlabel.setText(_translate("MainWindow", "X - Motion axis:"))
        self.YmotionLabel.setText(_translate("MainWindow", "Y - Motion axis:"))
        self.Xmicronslabel.setText(_translate("MainWindow", "Microns"))
        self.Ymicronslabel.setText(_translate("MainWindow", "Microns"))
        self.xybedaxisLabel_2.setText(_translate("MainWindow", "Origin:"))
        self.xlabel_2.setText(_translate("MainWindow", "x"))
        self.mmLabel_2.setText(_translate("MainWindow", "Millimeters"))
        self.PrinterSettingstab.setTabText(self.PrinterSettingstab.indexOf(self.Printer_Settings), _translate("MainWindow", "Printer Settings"))
        self.Console.setTabText(self.Console.indexOf(self.tab_6), _translate("MainWindow", "Console"))
        self.groupBoxstatus.setTitle(_translate("MainWindow", "Printer Status"))
        self.connection.setText(_translate("MainWindow", "Connection:"))
        self.currentprocess.setText(_translate("MainWindow", "Current Process:"))
        self.layerinfo.setText(_translate("MainWindow", "Selected Layer :"))
        self.cadmodelname.setText(_translate("MainWindow", "CAD Model Name:"))
        self.connectionstatus.setText(_translate("MainWindow", "Disconnected"))
        self.process.setText(_translate("MainWindow", "Idle"))


# if __name__.endswith('__main__'):
    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    # ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    # MainWindow.show()
    # sys.exit(app.exec_())

