# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stlSlicerr.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StlSlicer(object):
    def setupUi(self, StlSlicer):
        StlSlicer.setObjectName("StlSlicer")
        StlSlicer.resize(1281, 514)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StlSlicer.sizePolicy().hasHeightForWidth())
        StlSlicer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        StlSlicer.setFont(font)
        self.stlModellabel = QtWidgets.QLabel(StlSlicer)
        self.stlModellabel.setGeometry(QtCore.QRect(820, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.stlModellabel.setFont(font)
        self.stlModellabel.setScaledContents(True)
        self.stlModellabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stlModellabel.setWordWrap(False)
        self.stlModellabel.setObjectName("stlModellabel")
        self.groupBox = QtWidgets.QGroupBox(StlSlicer)
        self.groupBox.setGeometry(QtCore.QRect(810, 60, 461, 261))
        self.groupBox.setObjectName("groupBox")
        self.xlabel2 = QtWidgets.QLabel(self.groupBox)
        self.xlabel2.setGeometry(QtCore.QRect(219, 80, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2.setFont(font)
        self.xlabel2.setScaledContents(True)
        self.xlabel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2.setWordWrap(False)
        self.xlabel2.setObjectName("xlabel2")
        self.rx = QtWidgets.QSpinBox(self.groupBox)
        self.rx.setGeometry(QtCore.QRect(20, 180, 81, 31))
        self.rx.setMinimum(-2000)
        self.rx.setMaximum(2000)
        self.rx.setProperty("value", 0)
        self.rx.setObjectName("rx")
        self.auto_scale = QtWidgets.QPushButton(self.groupBox)
        self.auto_scale.setGeometry(QtCore.QRect(240, 30, 211, 31))
        self.auto_scale.setObjectName("auto_scale")
        self.tx = QtWidgets.QSpinBox(self.groupBox)
        self.tx.setGeometry(QtCore.QRect(21, 130, 81, 31))
        self.tx.setMinimum(-2000)
        self.tx.setMaximum(2000)
        self.tx.setProperty("value", 0)
        self.tx.setObjectName("tx")
        self.xlabel2_4 = QtWidgets.QLabel(self.groupBox)
        self.xlabel2_4.setGeometry(QtCore.QRect(111, 130, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2_4.setFont(font)
        self.xlabel2_4.setScaledContents(True)
        self.xlabel2_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2_4.setWordWrap(False)
        self.xlabel2_4.setObjectName("xlabel2_4")
        self.ScaleSTL = QtWidgets.QPushButton(self.groupBox)
        self.ScaleSTL.setGeometry(QtCore.QRect(330, 80, 121, 31))
        self.ScaleSTL.setObjectName("ScaleSTL")
        self.ry = QtWidgets.QSpinBox(self.groupBox)
        self.ry.setGeometry(QtCore.QRect(130, 180, 81, 31))
        self.ry.setMinimum(-2000)
        self.ry.setMaximum(2000)
        self.ry.setProperty("value", 0)
        self.ry.setObjectName("ry")
        self.xlabel2_3 = QtWidgets.QLabel(self.groupBox)
        self.xlabel2_3.setGeometry(QtCore.QRect(220, 130, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2_3.setFont(font)
        self.xlabel2_3.setScaledContents(True)
        self.xlabel2_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2_3.setWordWrap(False)
        self.xlabel2_3.setObjectName("xlabel2_3")
        self.xlabel2_5 = QtWidgets.QLabel(self.groupBox)
        self.xlabel2_5.setGeometry(QtCore.QRect(110, 180, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2_5.setFont(font)
        self.xlabel2_5.setScaledContents(True)
        self.xlabel2_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2_5.setWordWrap(False)
        self.xlabel2_5.setObjectName("xlabel2_5")
        self.TranslateSTL = QtWidgets.QPushButton(self.groupBox)
        self.TranslateSTL.setGeometry(QtCore.QRect(330, 130, 121, 31))
        self.TranslateSTL.setObjectName("TranslateSTL")
        self.xlabel2_2 = QtWidgets.QLabel(self.groupBox)
        self.xlabel2_2.setGeometry(QtCore.QRect(110, 80, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2_2.setFont(font)
        self.xlabel2_2.setScaledContents(True)
        self.xlabel2_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2_2.setWordWrap(False)
        self.xlabel2_2.setObjectName("xlabel2_2")
        self.tz = QtWidgets.QSpinBox(self.groupBox)
        self.tz.setGeometry(QtCore.QRect(241, 130, 81, 31))
        self.tz.setMinimum(-2000)
        self.tz.setMaximum(2000)
        self.tz.setProperty("value", 0)
        self.tz.setObjectName("tz")
        self.ty = QtWidgets.QSpinBox(self.groupBox)
        self.ty.setGeometry(QtCore.QRect(131, 130, 81, 31))
        self.ty.setMinimum(-2000)
        self.ty.setMaximum(2000)
        self.ty.setProperty("value", 0)
        self.ty.setObjectName("ty")
        self.RotateSTL = QtWidgets.QPushButton(self.groupBox)
        self.RotateSTL.setGeometry(QtCore.QRect(330, 180, 121, 31))
        self.RotateSTL.setObjectName("RotateSTL")
        self.rz = QtWidgets.QSpinBox(self.groupBox)
        self.rz.setGeometry(QtCore.QRect(240, 180, 81, 31))
        self.rz.setMinimum(-2000)
        self.rz.setMaximum(2000)
        self.rz.setProperty("value", 0)
        self.rz.setObjectName("rz")
        self.centerIt = QtWidgets.QPushButton(self.groupBox)
        self.centerIt.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.centerIt.setObjectName("centerIt")
        self.xlabel2_6 = QtWidgets.QLabel(self.groupBox)
        self.xlabel2_6.setGeometry(QtCore.QRect(220, 180, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlabel2_6.setFont(font)
        self.xlabel2_6.setScaledContents(True)
        self.xlabel2_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xlabel2_6.setWordWrap(False)
        self.xlabel2_6.setObjectName("xlabel2_6")
        self.layerheight_label = QtWidgets.QLabel(self.groupBox)
        self.layerheight_label.setGeometry(QtCore.QRect(20, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.layerheight_label.setFont(font)
        self.layerheight_label.setScaledContents(True)
        self.layerheight_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.layerheight_label.setWordWrap(False)
        self.layerheight_label.setObjectName("layerheight_label")
        self.stlModellabel_3 = QtWidgets.QLabel(self.groupBox)
        self.stlModellabel_3.setGeometry(QtCore.QRect(340, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.stlModellabel_3.setFont(font)
        self.stlModellabel_3.setScaledContents(True)
        self.stlModellabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stlModellabel_3.setWordWrap(False)
        self.stlModellabel_3.setObjectName("stlModellabel_3")
        self.desiredlayerheight = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.desiredlayerheight.setGeometry(QtCore.QRect(220, 221, 101, 31))
        self.desiredlayerheight.setDecimals(2)
        self.desiredlayerheight.setMaximum(1000.99)
        self.desiredlayerheight.setSingleStep(0.01)
        self.desiredlayerheight.setObjectName("desiredlayerheight")
        self.XScale = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.XScale.setGeometry(QtCore.QRect(20, 80, 81, 31))
        self.XScale.setDecimals(1)
        self.XScale.setMinimum(0.1)
        self.XScale.setSingleStep(0.1)
        self.XScale.setObjectName("XScale")
        self.YScale = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.YScale.setGeometry(QtCore.QRect(130, 80, 81, 31))
        self.YScale.setDecimals(1)
        self.YScale.setMinimum(0.1)
        self.YScale.setSingleStep(0.1)
        self.YScale.setObjectName("YScale")
        self.ZScale = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.ZScale.setGeometry(QtCore.QRect(240, 80, 81, 31))
        self.ZScale.setDecimals(1)
        self.ZScale.setMinimum(0.1)
        self.ZScale.setSingleStep(0.1)
        self.ZScale.setObjectName("ZScale")
        self.stlNameLabel = QtWidgets.QLabel(StlSlicer)
        self.stlNameLabel.setGeometry(QtCore.QRect(930, 20, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.stlNameLabel.setFont(font)
        self.stlNameLabel.setText("")
        self.stlNameLabel.setScaledContents(True)
        self.stlNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stlNameLabel.setWordWrap(False)
        self.stlNameLabel.setObjectName("stlNameLabel")
        self.SliceSTl = QtWidgets.QPushButton(StlSlicer)
        self.SliceSTl.setGeometry(QtCore.QRect(810, 330, 231, 41))
        self.SliceSTl.setObjectName("SliceSTl")
        self.OPenSlic3r = QtWidgets.QPushButton(StlSlicer)
        self.OPenSlic3r.setGeometry(QtCore.QRect(1060, 330, 211, 41))
        self.OPenSlic3r.setObjectName("OPenSlic3r")
        self.viewstl = QtWidgets.QWidget(StlSlicer)
        self.viewstl.setGeometry(QtCore.QRect(10, 10, 791, 490))
        self.viewstl.setObjectName("viewstl")
        self.StltextBrowser = QtWidgets.QTextBrowser(StlSlicer)
        self.StltextBrowser.setGeometry(QtCore.QRect(810, 380, 461, 121))
        self.StltextBrowser.setObjectName("StltextBrowser")

        self.retranslateUi(StlSlicer)
        QtCore.QMetaObject.connectSlotsByName(StlSlicer)

    def retranslateUi(self, StlSlicer):
        _translate = QtCore.QCoreApplication.translate
        StlSlicer.setWindowTitle(_translate("StlSlicer", "Dialog"))
        self.stlModellabel.setText(_translate("StlSlicer", "STL Model :"))
        self.groupBox.setTitle(_translate("StlSlicer", "Settings:"))
        self.xlabel2.setText(_translate("StlSlicer", "x"))
        self.auto_scale.setText(_translate("StlSlicer", "Auto Scale"))
        self.xlabel2_4.setText(_translate("StlSlicer", "x"))
        self.ScaleSTL.setText(_translate("StlSlicer", "Scale X-Y-Z"))
        self.xlabel2_3.setText(_translate("StlSlicer", "x"))
        self.xlabel2_5.setText(_translate("StlSlicer", "x"))
        self.TranslateSTL.setText(_translate("StlSlicer", "Translate X-Y-Z"))
        self.xlabel2_2.setText(_translate("StlSlicer", "x"))
        self.RotateSTL.setText(_translate("StlSlicer", "Rotate X-Y-Z"))
        self.centerIt.setText(_translate("StlSlicer", "Center"))
        self.xlabel2_6.setText(_translate("StlSlicer", "x"))
        self.layerheight_label.setText(_translate("StlSlicer", "Desired layer height :"))
        self.stlModellabel_3.setText(_translate("StlSlicer", "    mm"))
        self.SliceSTl.setText(_translate("StlSlicer", "Slice Stl"))
        self.OPenSlic3r.setText(_translate("StlSlicer", "Open Slic3r"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StlSlicer = QtWidgets.QDialog()
    ui = Ui_StlSlicer()
    ui.setupUi(StlSlicer)
    StlSlicer.show()
    sys.exit(app.exec_())

